"""add subcategory to products

Revision ID: b65bb2e1a9e0
Revises: f8480ecbd877
Create Date: 2026-07-09 22:36:55.080092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65bb2e1a9e0'
down_revision: Union[str, Sequence[str], None] = 'f8480ecbd877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
