"""add color and rating to products

Revision ID: fbc61c56b6bc
Revises: b65bb2e1a9e0
Create Date: 2026-07-14 11:31:13.954032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc61c56b6bc'
down_revision: Union[str, Sequence[str], None] = 'b65bb2e1a9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour', sa.String(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    op.drop_column('products', 'colour')
    # ### end Alembic commands ###
